import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { Sidebar } from '../../components/dashboard/Sidebar';
import { logout } from '../../lib/auth';
import { toast } from 'sonner';
import {
  User,
  Bell,
  Shield,
  Building2,
  Eye,
  EyeOff,
  Save,
  Check,
  ShieldCheck,
  CheckCheck,
  BellOff,
} from 'lucide-react';
import { 
  SectionCard, 
  Field, 
  TextInput, 
  Toggle, 
  SaveButton 
} from '../../components/dashboard/SettingsComponents';
import { ProfileSection } from './ProfileSection'; // Corrected import path
import {
  type AppNotification,
  type ActivityLogEntry,
} from '../../lib/store';
import { api } from '../../lib/api';
import { getSession } from '../../lib/auth'; // Import getSession from lib/auth

type Tab = 'profile' | 'notifications' | 'system' | 'security';

// ── Tab Sections ─────────────────────────────────────────────────────────────

function NotificationsSection() {
  const session = getSession(); // Assuming getSession still works for current user ID
  const recipientId = session?.id || 'admin'; // Fallback to 'admin' if session ID is not available
  const [notifications, setNotifications] = useState<AppNotification[]>([]);

  const fetchNotifications = async () => {
    if (!recipientId) return;
    try {
      const data = await api.get(`/users/${recipientId}/notifications`);
      setNotifications(data);
    } catch (error) {
      console.error('Failed to fetch notifications:', error);
      toast.error('Failed to load notifications.');
    }
  };

  useEffect(() => {
    fetchNotifications();
  }, [recipientId]);

  const unreadCount = notifications.filter((n) => !n.read).length;

  const handleMarkRead = async (id: string) => {
    try {
      await api.patch(`/users/${recipientId}/notifications/${id}`, { read: true });
      fetchNotifications(); // Re-fetch to update UI
    } catch (error) {
      toast.error('Failed to mark notification as read.');
    }
  };

  const handleMarkAllRead = async () => {
    try {
      await api.patch(`/users/${recipientId}/notifications/mark-all-read`, {});
      fetchNotifications(); // Re-fetch to update UI
    } catch (error) {
      toast.error('Failed to mark all notifications as read.');
    }
  };

  const formatTime = (iso: string) => {
    const d = new Date(iso);
    return d.toLocaleString('en-NG', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: true,
    });
  };

  return (
    <div className="space-y-6">
      <SectionCard
        title="Notifications"
        description="System notifications generated by staff actions across the portal."
      >
        {notifications.length > 0 && unreadCount > 0 && (
          <div className="flex justify-end mb-4">
            <button
              onClick={handleMarkAllRead}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-gray-300 bg-gray-700 hover:bg-gray-600 rounded-lg transition-colors"
            >
              <CheckCheck className="w-3.5 h-3.5" />
              Mark all as read
            </button>
          </div>
        )}

        {notifications.length === 0 ? (
          <div className="flex flex-col items-center gap-3 py-12">
            <div className="w-12 h-12 bg-gray-700 rounded-full flex items-center justify-center">
              <BellOff className="w-6 h-6 text-gray-500" />
            </div>
            <p className="text-gray-400 font-medium text-sm">No notifications yet</p>
            <p className="text-gray-500 text-xs text-center">
              You'll see alerts here when managers submit reports, expenses, or balance requests.
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {notifications.map((notif) => (
              <div
                key={notif.id}
                onClick={() => !notif.read && handleMarkRead(notif.id)}
                className={`flex items-start gap-3 p-3.5 rounded-lg border transition-colors ${
                  notif.read
                    ? 'border-gray-700 bg-transparent opacity-60'
                    : 'border-primary/20 bg-primary/5 cursor-pointer hover:bg-primary/10'
                }`}
              >
                <div className={`w-2 h-2 rounded-full mt-1.5 flex-shrink-0 ${notif.read ? 'bg-gray-600' : 'bg-primary'}`} />
                <div className="flex-1 min-w-0">
                  <div className="flex items-start justify-between gap-2">
                    <p className={`text-sm font-medium ${notif.read ? 'text-gray-400' : 'text-white'}`}>
                      {notif.title}
                    </p>
                    {!notif.read && (
                      <span className="text-xs px-1.5 py-0.5 bg-primary/20 text-primary rounded-full flex-shrink-0">NEW</span>
                    )}
                  </div>
                  <p className="text-xs text-gray-400 mt-0.5 leading-relaxed">{notif.body}</p>
                  <p className="text-xs text-gray-600 mt-1">{formatTime(notif.createdAt)}</p>
                </div>
              </div>
            ))}
          </div>
        )}
      </SectionCard>
    </div>
  );
}

function SystemSection() {
  const [companyName, setCompanyName] = useState('Fredviv Oil and Gas Limited');
  const [reportDeadline, setReportDeadline] = useState('18:00');
  const [balanceDuration, setBalanceDuration] = useState('30');
  const [pinLength, setPinLength] = useState('6');
  const [timezone, setTimezone] = useState('Africa/Lagos');
  const [currency, setCurrency] = useState('NGN');
  const [saved, setSaved] = useState(false);

  const handleSave = () => {
    setSaved(true);
    toast.success('System settings saved');
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div className="space-y-6">
      <SectionCard
        title="Company Information"
        description="Basic details displayed across the staff portal."
      >
        <div className="grid sm:grid-cols-2 gap-4 mb-6">
          <Field label="Company Name" hint="Shown on login screen and portal headers">
            <TextInput value={companyName} onChange={setCompanyName} />
          </Field>
          <Field label="Default Currency">
            <select
              value={currency}
              onChange={(e) => setCurrency(e.target.value)}
              className="w-full px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="NGN">NGN — Nigerian Naira (₦)</option>
              <option value="USD">USD — US Dollar ($)</option>
              <option value="GBP">GBP — British Pound (£)</option>
            </select>
          </Field>
          <Field label="Timezone">
            <select
              value={timezone}
              onChange={(e) => setTimezone(e.target.value)}
              className="w-full px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="Africa/Lagos">Africa/Lagos (WAT, UTC+1)</option>
              <option value="UTC">UTC</option>
            </select>
          </Field>
        </div>
        <SaveButton onClick={handleSave} saved={saved} />
      </SectionCard>

      <SectionCard
        title="Operational Rules"
        description="Configure the rules that govern daily operations across all branches."
      >
        <div className="grid sm:grid-cols-2 gap-4 mb-6">
          <Field
            label="Daily Report Deadline"
            hint="Managers must submit their sales report before this time"
          >
            <input
              type="time"
              value={reportDeadline}
              onChange={(e) => setReportDeadline(e.target.value)}
              className="w-full px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </Field>

          <Field
            label="Balance Visibility Duration (seconds)"
            hint="How long the account balance remains visible after admin approval"
          >
            <select
              value={balanceDuration}
              onChange={(e) => setBalanceDuration(e.target.value)}
              className="w-full px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="15">15 seconds</option>
              <option value="30">30 seconds</option>
              <option value="60">60 seconds</option>
              <option value="120">2 minutes</option>
            </select>
          </Field>

          <Field
            label="Balance Request PIN Length"
            hint="Number of digits required in the accountant / auditor PIN"
          >
            <select
              value={pinLength}
              onChange={(e) => setPinLength(e.target.value)}
              className="w-full px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            >
              <option value="4">4 digits</option>
              <option value="6">6 digits</option>
            </select>
          </Field>
        </div>
        <SaveButton onClick={handleSave} saved={saved} />
      </SectionCard>
    </div>
  );
}

function SecuritySection() {
  const [sessionTimeout, setSessionTimeout] = useState('60');
  const [requirePinForBalance, setRequirePinForBalance] = useState(true);
  const [logActivity, setLogActivity] = useState(true);
  const [twoFactor, setTwoFactor] = useState(false);
  const [saved, setSaved] = useState(false);
  const [activityLog, setActivityLog] = useState<ActivityLogEntry[]>([]);

  useEffect(() => {
    const fetchLogs = async () => {
      try {
        const logs = await api.get('/system/activity-logs');
        setActivityLog(logs);
      } catch (error) {
        console.error('Failed to fetch activity logs');
      }
    };
    fetchLogs();
  }, []);

  const typeColors: Record<string, string> = {
    security: 'text-red-400',
    user: 'text-blue-400',
    price: 'text-yellow-400',
    balance: 'text-green-400',
    expense: 'text-purple-400',
  };

  const handleSave = () => {
    setSaved(true);
    toast.success('Security settings saved');
    setTimeout(() => setSaved(false), 2000);
  };

  return (
    <div className="space-y-6">
      <SectionCard
        title="Access & Session"
        description="Control how sessions and sensitive actions are handled across the portal."
      >
        <div className="mb-6">
          <div className="mb-4">
            <Field
              label="Session Timeout"
              hint="Automatically log out inactive users after this period"
            >
              <select
                value={sessionTimeout}
                onChange={(e) => setSessionTimeout(e.target.value)}
                className="w-full sm:w-64 px-4 py-2.5 bg-gray-700 border border-gray-600 rounded-lg text-white text-sm focus:outline-none focus:ring-2 focus:ring-primary"
              >
                <option value="15">15 minutes</option>
                <option value="30">30 minutes</option>
                <option value="60">1 hour</option>
                <option value="120">2 hours</option>
                <option value="480">8 hours</option>
              </select>
            </Field>
          </div>

          <div className="divide-y divide-gray-700">
            <Toggle
              checked={requirePinForBalance}
              onChange={setRequirePinForBalance}
              label="Require PIN for Balance Requests"
              description="Accountants and auditors must enter a PIN before balance visibility is granted"
            />
            <Toggle
              checked={logActivity}
              onChange={setLogActivity}
              label="Log Admin Activity"
              description="Keep a record of all admin actions including approvals, user changes, and price updates"
            />
            <Toggle
              checked={twoFactor}
              onChange={setTwoFactor}
              label="Two-Factor Authentication"
              description="Require an OTP in addition to password when logging in to the admin portal"
            />
          </div>
        </div>
        <SaveButton onClick={handleSave} saved={saved} />
      </SectionCard>

      <SectionCard
        title="Recent Admin Activity"
        description="A log of actions taken in the portal by this admin account."
      >
        {activityLog.length === 0 ? (
          <p className="text-gray-500 text-sm text-center py-8">No activity recorded yet.</p>
        ) : (
          <div className="space-y-0 divide-y divide-gray-700">
            {activityLog.map((entry) => (
              <div key={entry.id} className="flex items-center justify-between py-3">
                <p className={`text-sm font-medium ${typeColors[entry.type] ?? 'text-gray-300'}`}>
                  {entry.action}
                </p>
                <span className="text-xs text-gray-500 text-right flex-shrink-0 ml-4">
                  {entry.time}
                </span>
              </div>
            ))}
          </div>
        )}
      </SectionCard>
    </div>
  );
}

// ── Main Settings Page ────────────────────────────────────────────────────────

const TABS: { id: Tab; label: string; icon: React.ElementType; description: string }[] = [
  { id: 'profile', label: 'Profile', icon: User, description: 'Personal info & password' },
  { id: 'notifications', label: 'Notifications', icon: Bell, description: 'Alert preferences' },
  { id: 'system', label: 'System', icon: Building2, description: 'Operational rules' },
  { id: 'security', label: 'Security', icon: Shield, description: 'Access & activity log' },
];

export function Settings() {
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<Tab>('profile');

  const handleLogout = () => { logout(); navigate('/staff/login'); };

  return (
    <div className="flex min-h-screen bg-gray-900"> {/* Sidebar role prop updated to uppercase */}
      <Sidebar role="ADMIN" onLogout={handleLogout} />

      <div className="flex-1 overflow-x-hidden">
        {/* Header */}
        <header className="bg-gray-800 border-b border-gray-700 sticky top-0 z-40">
          <div className="px-6 py-4">
            <h1 className="text-2xl font-bold text-white">Settings</h1>
            <p className="text-gray-400 text-sm">Manage your account, notifications, and system configuration</p>
          </div>
        </header>

        <main className="p-6">
          <div className="max-w-5xl mx-auto flex gap-6 items-start">
            {/* Tab Nav */}
            <nav className="w-56 flex-shrink-0 bg-gray-800 border border-gray-700 rounded-xl overflow-hidden sticky top-24">
              {TABS.map((tab) => {
                const Icon = tab.icon;
                const isActive = activeTab === tab.id;
                return (
                  <button
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    className={`w-full flex items-center gap-3 px-4 py-3.5 text-left transition-colors border-b border-gray-700 last:border-0 ${
                      isActive
                        ? 'bg-primary/10 border-r-2 border-r-primary text-white'
                        : 'text-gray-300 hover:bg-gray-700/50 hover:text-white'
                    }`}
                  >
                    <Icon className={`w-4 h-4 flex-shrink-0 ${isActive ? 'text-primary' : 'text-gray-400'}`} />
                    <div className="min-w-0">
                      <p className="text-sm font-medium leading-tight">{tab.label}</p>
                      <p className="text-xs text-gray-500 leading-tight mt-0.5">{tab.description}</p>
                    </div>
                  </button>
                );
              })}
            </nav>

            {/* Tab Content */}
            <div className="flex-1 min-w-0">
              {activeTab === 'profile' && <ProfileSection roleLabel="Super Administrator" isAdmin={true} />}
              {activeTab === 'notifications' && <NotificationsSection />}
              {activeTab === 'system' && <SystemSection />}
              {activeTab === 'security' && <SecuritySection />}
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
